### ISSUE TITLE
Make software do something!

### ISSUE THREAD

**Issue by GregWoods** [jonata/opendvdproducer#1]
So far there seems to be a nice looking UI, and a nice web site to go with it, but the WIndows version of the app does nothing. I can add videos, but I can't preview them. Adding menus looks as though it is not implemented yet. There is no way to create an iso or DVD. 
It looks like the website and associated marketing on Wikipedia were premature :(

**Comment by jonata** [comment]
Hi Greg!

I am sorry the released version did not work for you. We are developing mainly on Linux and Mac platform and to be sincere, the Windows version is not our priority since the beginning of the development. At the same time, we are sure that this software would be useful to those who use Windows. As you can note on the page http://opendvdproducer.jonata.org/windows.html the pointed issues are known and we are researching some way to fix them.

Talking about the "marketing", we believe that those who use Linux and Mac do not have such bad experience and the features shown on the website are accurate.

Thanks for your attention!

**Comment by GregWoods** [comment]
Thank you for your speedy reply.
I understand the need to prioritse one platform over another, but if the
Windows version does not work (my PC meets the requirements), don't release
it or market it.
I've been looking around, and the selection of DVD Authoring packages on
Windows is terrible. Many are trials, others are bundled with crapware. The
ones which do work have terrible UI (your's looks nice and easy and logical)
OSX already has Burn, which I have used for DVD writing, but not for
DVD-Video authoring - so the market for a new app on OSX may not be there.

Anyway.. I look forward to seeing your project progress. In the meantime, I
will try the OSX version.

Best Wishes

Greg

**Comment by jonata** [comment]
Thanks Greg.

Be sure we will try to fix the issues.

**Comment by jonata** [comment]
Hey Greg

I think you will like to know that we fixed some issues on Windows build. Please, check the version 15.10.2.

Thanks for your attention.

**Comment by Auerhahn** [comment]
Nice to hear that this software now does something under Windows. Will the Mac version do something in the future? For now I can add a video but no menu. So I can do just absolutely nothing with it. May be it was a little bit (2 or three years) to early for the release?

**Comment by jonata** [comment]
Hi Auerhahn

Please, could you provide some more information about this? For example, what kind of file are you trying to use for the menu? What is the operating system you are using?

With all respect, if you see that this software is not good for you and you will not be able to help reporting bugs, you are free to use any other better software.

But thanks for the suggestion, I will consider stopping the development and taking it off github.

**Comment by jonata** [comment]
By the way, I was thinking... did you notice the button "Use menus" on the project details tab? You can use Menus in your project if you select this option.
