### ISSUE TITLE
Overlay graphic

### ISSUE THREAD

**Issue by MikoPi** [jonata/opendvdproducer#6]
Hello
I cant understand how overlay image works. Have I create it the same like main picture but with different colours?

**Comment by MikoPi** [comment]
And one more think. I can not find the way to remove overlay image once imported.

**Comment by jonata** [comment]
Hi MikoPi

The overlay image is just a mask, one color, that represents what will be highlighted on menu while the user walk through the buttons. The color you use in the image can be any color, but I use to draw in black. OpenDVDProducer will consider the "contrast" of the image.

The option to remove the overlay image, and the background image of menu, is fixed in 84f7f3e.

Thanks for your attention, and sorry by the late :smile:
